server:
  port: 0  # Notification 서비스 고정 포트

spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:"  # Config Server에서 설정 불러오기
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus  # Actuator 헬스체크 및 모니터링

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: ${HOSTNAME:localhost}
#    prefer-ip-address: true  # IP 기반 서비스 등록
