version: '3.8'
services:
  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server

  gateway-server:
    build: ./gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8110:8110"
    depends_on:
      - eureka-server

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8120:8120"
    depends_on:
      - eureka-server

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8130:8130"
    depends_on:
      - eureka-server

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    ports:
      - "8140:8140"
    depends_on:
      - eureka-server

  flight-service:
    build: ./flight-service
    container_name: flight-service
    ports:
      - "8150:8150"
    depends_on:
      - eureka-server

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8160:8160"
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flight_booking
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_MAIL_USERNAME: Carry9691@gmail.com
      SPRING_MAIL_PASSWORD: xrxt hjjz bwlg atlm
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: flight_booking
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command:
      - -config.file=/etc/promtail/config.yml

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
