
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  zookeeper_data:
  kafka_data:

services:
  # 2️⃣ Eureka Server
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  # 3️⃣ Config Server
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  # 4️⃣ Gateway Service
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SECRET_KEY: ${SECRET_KEY}

  # 1️⃣ Common Module (공통 모듈)
  common:
    build:
      context: ./common
    container_name: common
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      gateway-service:
        condition: service_healthy
    restart: always # depends_on 제거, restart 정책 추가


  # 5️⃣ PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 6️⃣ Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # 7️⃣ Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "8090:8090"  # Admin Server 포트
    networks:
      - app-network
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - ./zookeeper.properties:/etc/kafka/zookeeper.properties
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT:-2181}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME:-2000}
      ZOOKEEPER_SYNC_LIMIT: ${ZOOKEEPER_SYNC_LIMIT:-2}
      ZOOKEEPER_INIT_LIMIT: ${ZOOKEEPER_INIT_LIMIT:-5}
      ZOOKEEPER_ADMIN_SERVER_ENABLED: "true"
      ZOOKEEPER_ADMIN_SERVER_PORT: 8090  # Admin Server 포트 변경
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok,srvr,stat,conf,mntr"
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok,srvr,stat,conf,mntr"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8090/commands || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 8️⃣ Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    volumes:
      - kafka_data:/var/lib/kafka/data
    env_file:
      - .env
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID:-1}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT:-zookeeper:2181}
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:-1}
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      # 메시지 크기 조정
      KAFKA_MESSAGE_MAX_BYTES: 2000000000  # 2GB (최대 허용값)
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2000000000
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 2000000000
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2000000000
      KAFKA_HEAP_OPTS: "-Xms1g -Xmx1300m"
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 20s
      timeout: 10s
      retries: 10

  # 9️⃣ Zipkin (분산 추적)
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9411/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🔟 Prometheus (모니터링)
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  # 11️⃣ Grafana (시각화)
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

  # 🔔 Notification Service
  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    ports:
      - "8160:8160"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    env_file:
      - .env

  # 🔑 User Service
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8100:8100"
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    env_file:
      - .env

  # 📦 Booking Service
  booking-service:
    build:
      context: ./booking-service
    container_name: booking-service
    ports:
      - "8120:8120"
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    env_file:
      - .env

  # 💳 Payment Service
  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    ports:
      - "8130:8130"
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    env_file:
      - .env

  # ✈️ Flight Service
  flight-service:
    build:
      context: ./flight-service
    container_name: flight-service
    ports:
      - "8150:8150"
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    env_file:
      - .env

  # 🎟️ Ticket Service
  ticket-service:
    build:
      context: ./ticket-service
    container_name: ticket-service
    ports:
      - "8140:8140"
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    env_file:
      - .env
