version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - app-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8100:8100"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      DB_HOST: production-db-host
      DB_PORT: 3306
      DB_NAME: user_db
      DB_USER: prod_user
      DB_PASSWORD: prod_password

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8120:8120"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      DB_HOST: production-db-host
      DB_PORT: 3306
      DB_NAME: booking_db
      DB_USER: prod_user
      DB_PASSWORD: prod_password

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8130:8130"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      DB_HOST: production-db-host
      DB_PORT: 3306
      DB_NAME: payment_db
      DB_USER: prod_user
      DB_PASSWORD: prod_password

  ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    ports:
      - "8140:8140"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      DB_HOST: production-db-host
      DB_PORT: 3306
      DB_NAME: ticket_db
      DB_USER: prod_user
      DB_PASSWORD: prod_password

  flight-service:
    build: ./flight-service
    container_name: flight-service
    ports:
      - "8150:8150"
    networks:
      - app-network
    depends_on:
      - eureka-server
    environment:
      DB_HOST: production-db-host
      DB_PORT: 3306
      DB_NAME: flight_db
      DB_USER: prod_user
      DB_PASSWORD: prod_password

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8160:8160"
    networks:
      - app-network
    depends_on:
      - eureka-server
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flight_booking
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-your_email@example.com}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-your_password}
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: flight_booking
    ports:
      - "5432:5432"
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network
