global:
  scrape_interval: 15s
  evaluation_interval: 15s  # 경고 조건 평가 주기

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  # Alertmanager와 연동

scrape_configs:
  - job_name: 'eureka-server'
    static_configs:
      - targets: ['eureka-server:8761']
  # config server 모니터링
  - job_name: 'config-server'
    static_configs:
      - targets: ['config-service:8888']
  # 1️⃣ Gateway Service 모니터링
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway-service:8080']

  # 2️⃣ User Service 모니터링
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8100']

  # 3️⃣ Booking Service 모니터링
  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8120']

  # 4️⃣ Payment Service 모니터링
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8130']

  # 5️⃣ Ticket Service 모니터링
  - job_name: 'ticket-service'
    static_configs:
      - targets: ['ticket-service:8140']

  # 6️⃣ Flight Service 모니터링
  - job_name: 'flight-service'
    static_configs:
      - targets: ['flight-service:8150']

  # 7️⃣ Notification Service 모니터링
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8160']

  # 8️⃣ Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Zookeeper 모니터링
  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

#  # Kafka 모니터링
#  - job_name: 'kafka'
#    static_configs:
#      - targets: ['kafka:9092']
