server:
  port: 0  # flight-service는 8150 포트 사용

spring:
  application:
    name: flight-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: true
