server:
  port: 0  # Temporary port, will be overwritten by Config server settings later.

spring:
  application:
    name: flight-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/