server:
  port: 8150  # flight-service는 8150 포트 사용

spring:
  application:
    name: flight-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

management:
  tracing:
    sampling:
      probability: 1.0  # 전체 트레이싱 활성화
    zipkin:
      endpoint: http://zipkin:9411/api/v2/spans  # localhost 대신 zipkin 서비스 이름 사용
  endpoints:
    web:
      exposure:
        include: prometheus


eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

