server:
  port: 0 # Config Server에서 포트 설정

spring:
  application:
    name: booking-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/