server:
  port: 0

spring:
  application:
    name: booking-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청 추적
    zipkin:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: true
