server:
  port: 8080

spring:
  application:
    name: gateway-service

  main:
    web-application-type: reactive  # ✅ 추가

  config:
    import: "optional:configserver:"

  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
