server:
  port: 0  # 임시 포트, Config Server에서 덮어씌워짐

spring:
  application:
    name: gateway-service
  config:
    import: "configserver:"  # Config Server에서 설정 가져오기
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/