server:
  port: 8888  # Gateway 서비스는 일반적으로 8080 포트를 사용

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-server:8888  # Config Server에서 설정 불러오기
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

management:
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
