server:
  port: 0  # 임시 포트, Config Server에서 덮어씌워짐

spring:
  application:
    name: payment-service
  config:
    import: "configserver:"  # Config Server에서 설정 가져오기
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  datasource:
    url: jdbc:h2:mem:test;  # H2: test용 인메모리 DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: TRACE

eureka:
  client:
    register-with-eureka: true   # Eureka에 서비스 등록
    fetch-registry: true         # 다른 서비스 정보 조회
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true      # IP 주소로 등록
