server:
  port: 0  # Temporary port, will be overwritten by Config server settings later.

spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:"  # Retrieve configuration from Config Server (application can run even if Config Server is not available)
  cloud:
    config:
      discovery:
        enabled: true  # Discover Config Server through Eureka
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://172.20.0.5:8761/eureka/  # Use Eureka server name within Docker network
