server:
  port: 8761

spring:
  application:
    name: eureka-server


management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]  # 프로메테우스로만 볼꺼라 다르 엔드포인트는 없어도 될듯싶은
  endpoint: # 빼도 됨
    health:
      show-details: always  # 헬스 체크 상세 정보 제공

eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}

  server:
    enableSelfPreservation: ${EUREKA_SERVER_SELF_PRESERVATION:false}

#logging:
#  level:
#    com.netflix.discovery: DEBUG # 배포시 INFO로  # 패키지 위치가..?? -> 출력 안될 것, @Sl4j 쓰는게 좋아보임