server:
  port: 8080

service:
  jwt:
    access-expiration: 86400000  # 24시간
    secret-key: ${SECRET_KEY}


spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service  # 애플리케이션 이름을 'gateway-service'로 설정
  cloud:
    gateway:
      routes: # Spring Cloud Gateway의 라우팅 설정
        - id: user-service  # 라우트 식별자
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**
            - Path=/v1/auth/**
        - id: payment-service  # 라우트 식별자
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: flight-service  # 라우트 식별자
          uri: lb://flight-service
          predicates:
            - Path=/api/flights/**
        - id: ticket-service  # 라우트 식별자
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**
        - id: booking-service  # 라우트 식별자
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**

      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"  # Zipkin 서버의 엔드포인트 지정
  tracing:
    sampling:
      probability: 1.0  # Zipkin 트레이싱 샘플링 비율 (1.0: 100%)
  endpoints:
    web:
      exposure:
        include: refresh  # [Post] /actuator/refresh 엔드포인트 노출 (config server 변경사항 수동 갱신)
