server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**, /v1/auth/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/v1/payments/**
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/v1/flights/**
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/v1/tickets/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/v1/bookings/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: refresh, prometheus
