spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

server:
  port: 8888

eureka:
  client:
    # Eureka 서버의 기본 서비스 URL
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    # Config Server도 Eureka에 등록
    register-with-eureka: true
    fetch-registry: true
