server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          username: ${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
          password: ${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
          default-label: dev
          search-paths: '{application}'
          clone-on-start: true
          basedir: /tmp/config-repo
          skip-ssl-validation: true

management:
  tracing:
    sampling:
      probability: 1.0  # 모든 요청 추적
    zipkin:
      endpoint: http://zipkin:9411/api/v2/spans  # ✅ 최신 Zipkin 엔드포인트 적용
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: true
