server:
  port: 8888

spring:
  profiles:
    active: git  # 'git' 프로파일을 활성화 (선택사항)
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cool-Potatoes/config-repo.git # 이렇게보단 config용 레포를 하나 만드시는게
          username:
          password:
          default-label: main
          search-paths: '{application}'  # 애플리케이션 이름에 맞는 설정 파일을 찾음
          clone-on-start: true
#          basedir: /tmp/config-repo  # 원격에서 가져올때는 필요 없는 설정
          skip-ssl-validation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

