server:
  port: 8888

spring:
  application:
    name: config-server
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Cool-Potatoes/flight-booking.git
          default-label: dev
          search-paths: '{application}'
          clone-on-start: true
          ignore-local-ssh-settings: false  # SSH 설정 사용
          basedir: /tmp/config-repo
          skip-ssl-validation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
