spring:
  application:
    name: config-server # 애플리케이션 이름 설정
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

eureka.instance:
  hostname: localhost
