server:
  port: 8888  # 포트를 명시적으로 지정합니다.

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
      # Eureka Server를 통해 Config Server를 찾도록 설정합니다.
      discovery:
        enabled: true
        service-id: config-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/