server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
      discovery:
        enabled: true
        service-id: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://172.20.0.5:8761/eureka/
  instance:
    hostname: config-server
    nonSecurePort: 8888
logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG