server:
  port: 0  # Temporary port, will be overwritten by Config server settings later.

spring:
  application:
    name: ticket-service
  config:
    import: "optional:configserver:"  # Retrieve configuration from Config Server (application can run even if Config Server is not available)
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    register-with-eureka: true   # Eureka에 서비스 등록
    fetch-registry: true         # 다른 서비스 정보 조회
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true      # IP 주소로 등록
