#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'zulu'
#
#      - name: Set Environment Variables
#        run: |
#          echo "DB_URL=jdbc:postgresql://localhost:5432/mydatabase" >> $GITHUB_ENV
#          echo "DB_USERNAME=myuser" >> $GITHUB_ENV
#          echo "DB_PASSWORD=mypassword" >> $GITHUB_ENV
#
#      - name: Grant execute permission for Gradle Wrapper
#        run: chmod +x */gradlew
#
#      - name: Build and Test Config Server
#        working-directory: config-server
#        run: ./gradlew build
#
#      - name: Start Config Server
#        working-directory: config-server
#        run: nohup java -jar build/libs/config-server-*.jar &
#
#      - name: Wait for Config Server
#        run: |
#          until curl -s http://localhost:8888/actuator/health | grep '"status":"UP"'; do
#            echo "Waiting for Config Server..."
#            sleep 5
#          done
#
#      - name: Build and Test Eureka Server
#        working-directory: eureka-server
#        run: ./gradlew build
