name: CI/CD using GitHub Actions & Docker

on:
  push:
    branches:
      - "dev"
      - "main"
      - "feat/cicd/action"

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 레포지토리 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # 3️⃣ Gradle 의존성 캐시
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4️⃣ Gradle Wrapper 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 5️⃣ Gradle 빌드 및 테스트
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Test with Gradle
        run: ./gradlew test

      # 6️⃣ DockerHub 로그인
      - name: DockerHub Login
        if: success() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 7️⃣ Docker 이미지 빌드 및 푸시 (서비스 이름 제거) (main 브랜치 푸시 시에만 실행)
      - name: Build and Push Docker Images
        if: success() && github.ref == 'refs/heads/main'
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker-compose -f docker-compose.yml build --build-arg VERSION=$IMAGE_TAG  #  전체 서비스 빌드
          docker-compose -f docker-compose.yml push  #  전체 서비스 푸시

      # 8️⃣ 개발 서버에 배포 (Docker 이미지 빌드 및 푸시 성공 시 실행)
      - name: Deploy to dev
        if: success() && github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/flight-booking  # EC2 서버의 프로젝트 경로로 이동
            docker-compose down  # 기존 컨테이너 중지
            docker-compose pull eureka-server config-server gateway-service notification-service user-service booking-service payment-service flight-service ticket-service  # 최신 이미지 다운로드
            docker-compose up -d --build eureka-server config-server gateway-service notification-service user-service booking-service payment-service flight-service ticket-service  # 컨테이너 재시작 및 배포
            docker image prune -af  # 사용하지 않는 Docker 이미지 정리